services:
  database:
    build: 
      context: ./Docker-files/db
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

  vproapp:
    build:
      context: ./Docker-files/app
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

volumes:
   vprodbdata: {}
   vproappdata: {}